=== lulonglong/project1-server/WebContent/WEB-INF/conf/validateParam.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.example.net/test" targetNamespace="http://www.example.net/test"
	elementFormDefault="qualified">

	<xsd:element name="validators" type="validators"></xsd:element>

	<xsd:element name="servletValidator" type="servletValidator"></xsd:element>

	<xsd:complexType name="servletValidator">
		<xsd:sequence>
			<xsd:element ref="validator" maxOccurs="unbounded"
				minOccurs="1">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="servletUrl" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="validator">
		<xsd:sequence>
			<xsd:element ref="validateParam" maxOccurs="unbounded"
				minOccurs="1">
			</xsd:element>
		</xsd:sequence>

		<xsd:attribute name="validatorClass" type="xsd:string"
			use="required"></xsd:attribute>
		<xsd:anyAttribute processContents="lax"/>
	</xsd:complexType>


	<xsd:complexType name="validateParam">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="errorCode" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:element name="validator" type="validator"></xsd:element>
	<xsd:element name="validateParam" type="validateParam"></xsd:element>


    <xsd:complexType name="validators">
    	<xsd:sequence>
    		<xsd:element ref="servletValidator" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    
</xsd:schema>

=== lulonglong/project1-server/WebContent/WEB-INF/conf/validateParam.xml
<?xml version="1.0" encoding="UTF-8"?>
<validators xmlns="http://www.example.net/test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.net/test validateParam.xsd">

	<!--ValidateRegister -->
	<servletValidator servletUrl="/ValidateRegister">

		<validator validatorClass="locationshare.validator.NullValidator">
			<validateParam name="username" errorCode="010101" />
		</validator>
		<validator validatorClass="locationshare.validator.RegexValidator"
			pattern="[a-z0-9A-Z-_@.]+">
			<validateParam name="username" errorCode="010102" />
		</validator>

	</servletValidator>

	<!--SignUp -->
	<servletValidator servletUrl="/SignUp">
		<validator validatorClass="locationshare.validator.RegexValidator"
			pattern="[012]">
			<validateParam name="type" errorCode="020101" />
		</validator>
		<validator validatorClass="locationshare.validator.NullValidator">
			<validateParam name="username" errorCode="020102" />
			<validateParam name="phoneos" errorCode="020105" />
			<validateParam name="devicename" errorCode="020106" />
		</validator>
		<validator validatorClass="locationshare.validator.RegexValidator"
			pattern="[a-z0-9A-Z-_@.]+">
			<validateParam name="username" errorCode="020103" />
		</validator>
	</servletValidator>

	<!--LogIn -->
	<servletValidator servletUrl="/LogIn">
		<validator validatorClass="locationshare.validator.RegexValidator"
			pattern="[012]">
			<validateParam name="type" errorCode="030101" />
		</validator>
		<validator validatorClass="locationshare.validator.NullValidator">
			<validateParam name="username" errorCode="030102" />
		</validator>
		<validator validatorClass="locationshare.validator.RegexValidator"
			pattern="[a-z0-9A-Z-_@.]+">
			<validateParam name="username" errorCode="030103" />
		</validator>
	</servletValidator>

	<!--RecordLogInInfo -->
	<servletValidator servletUrl="/RecordLogInInfo">
		<validator validatorClass="locationshare.validator.RegexValidator"
			pattern="[0-9]+">
			<validateParam name="userid" errorCode="040102" />
		</validator>
		<validator validatorClass="locationshare.validator.NullValidator">
			<validateParam name="userid" errorCode="040101" />
			<validateParam name="phoneos" errorCode="040103" />
			<validateParam name="devicename" errorCode="040104" />
		</validator>
	</servletValidator>
	
</validators>
